.PHONY: build test ruff clean ci

PYTHON = uv run python
BUILD_SCRIPT = build.py
SRC_DIR = plotly_lvlos
TEST_DIR = tests

build:
	@echo " Building project..."

	$(PYTHON) $(BUILD_SCRIPT)
	@echo "Build complete."

test:
	@echo "Running tests..."
	$(PYTHON) -m pytest $(TEST_DIR) --disable-warnings -v

ruff:
	@echo "Linting code with ruff..."
	$(PYTHON) -m ruff format $(SRC_DIR) $(TEST_DIR)
	$(PYTHON) -m ruff check $(SRC_DIR) $(TEST_DIR)

clean:
	@echo "Cleaning cache..."
	rm -rf __pycache__ */__pycache__

ci: clean build ruff test
	@echo "CI tasks completed successfully!"



#         countries_subset = [
#             "Afghanistan",
#             "Angola",
#             "Albania",
#             "Andorra",
#             "United Arab Emirates",
#             "Argentina",
#             "Armenia",
#             "Antigua and Barbuda",
#             "Australia",
#             "Austria",
#             "Azerbaijan",
#             "Burundi",
#             "Belgium",
#             "Benin",
#             "Burkina Faso",
#             "Bangladesh",
#             "Bulgaria",
#             "Bahrain",
#             "Bahamas",
#             "Bosnia and Herzegovina",
#             "Belarus",
#             "Belize",
#             "Bolivia",
#             "Brazil",
#             "Barbados",
#             "Brunei",
#             "Bhutan",
#             "Botswana",
#             "Central African Republic",
#             "Canada",
#             "Switzerland",
#             "Chile",
#             # "China",
#             # "Cote d'Ivoire", # problem
#             "Cameroon",
#             "Congo, Dem. Rep.",  # care
#             # "Congo, Rep.",  # care
#             "Colombia",
#             "Comoros",
#             "Cape Verde",
#             "Costa Rica",
#             "Cuba",
#             "Cyprus",
#             "Czech Republic",
#             "Germany",
#             "Djibouti",
#             "Dominica",
#             "Denmark",
#             "Dominican Republic",
#             "Algeria",
#             "Ecuador",
#             "Egypt",
#             "Eritrea",
#             "Spain",
#             "Estonia",
#             "Ethiopia",
#             "Finland",
#             "Fiji",
#             "France",
#             # "Micronesia, Fed. Sts.",  # care
#             "Gabon",
#             "United Kingdom",
#             "Georgia",
#             "Ghana",
#             "Guinea",
#             "Gambia",
#             "Guinea-Bissau",
#             "Equatorial Guinea",
#             "Greece",
#             "Grenada",
#             "Guatemala",
#             "Guyana",
#             # "Hong Kong, China",  # care
#             # "Honduras",
#             # "Croatia",
#             # "Haiti",
#             # "Hungary",
#             # "Indonesia",
#             # "India",
#             # "Ireland",
#             # "Iran",
#             # "Iraq",
#             # "Iceland",
#             # "Israel",
#             # "Italy",
#             # "Jamaica",
#             # "Jordan",
#             # "Japan",
#             # "Kazakhstan",
#             # "Kenya",
#             # "Kyrgyz Republic",
#             # "Cambodia",
#             # "Kiribati",
#             # "St. Kitts and Nevis",
#             # "South Korea",
#             # "Kuwait",
#             # "Lao",
#             # "Lebanon",
#             # "Liberia",
#             # "Libya",
#             # "St. Lucia",  # care
#             # "Sri Lanka",
#             # "Lesotho",
#             # "Lithuania",
#             # "Luxembourg",
#             # "Latvia",
#             # "Morocco",
#             # "Monaco",
#             # "Moldova",
#             # "Madagascar",
#             # "Maldives",
#             # "Mexico",
#             # "Marshall Islands",
#             # "North Macedonia",
#             # "Mali",
#             # "Malta",
#             # "Myanmar",
#             # "Montenegro",
#             # "Mongolia",
#             # "Mozambique",
#             # "Mauritania",
#             # "Mauritius",
#             # "Malawi",
#             # "Malaysia",
#             # "Namibia",
#             # "Niger",
#             # "Nigeria",
#             # "Nicaragua",
#             # "Netherlands",
#             # "Norway",
#             # "Nepal",
#             # "Nauru",
#             # "New Zealand",
#             # "Oman",
#             # "Pakistan",
#             # "Panama",
#             # "Peru",
#             # "Philippines",
#             # "Palau",
#             # "Papua New Guinea",
#             # "Poland",
#             # "North Korea",
#             # "Portugal",
#             # "Paraguay",
#             # "Palestine",
#             # "Qatar",
#             # "Romania",
#             # "Russia",
#             # "Rwanda",
#             # "Saudi Arabia",
#             # "Sudan",
#             # "Senegal",
#             # "Singapore",
#             # "Solomon Islands",
#             # "Sierra Leone",
#             # "El Salvador",
#             # "San Marino",
#             # "Somalia",
#             # "Serbia",
#             # "South Sudan",
#             # "Sao Tome and Principe",
#             # "Suriname",
#             # "Slovak Republic",
#             # "Slovenia",
#             # "Sweden",
#             # "Eswatini",
#             # "Seychelles",
#             # "Syria",
#             # "Chad",
#             # "Togo",
#             # "Thailand",
#             # "Tajikistan",
#             # "Turkmenistan",
#             # "Timor-Leste",  # care
#             # "Tonga",
#             # "Trinidad and Tobago",
#             # "Tunisia",
#             # "Turkey",
#             # "Tuvalu",
#             # "Taiwan",
#             # "Tanzania",
#             # "Uganda",
#             # "Ukraine",
#             # "Uruguay",
#             # "United States",
#             # "Uzbekistan",
#             # "St. Vincent and the Grenadines",  # care
#             # "Venezuela",
#             # "Vietnam",
#             # "Vanuatu",
#             # "Samoa",
#             # "Yemen",
#             # "South Africa",
#             # "Zambia",
#             # "Zimbabwe",
#         ]